### PR TITLE
Us 1

### PR DESCRIPTION
**Pull request by tcatherm**

### CODE REVIEW

**Comment by ghost** [comment]
Where you able to get it to compile?

I can't seem to make it compile.

**Comment by ghost** [comment]
Nevermind I got it

**Comment by tcatherm** [comment]
I don't have any issues compiling or running it, what error are you getting?

**Comment by ghost** [comment]
[java] Loaded from C:\Users\brian.memoranda\memoranda.properties
     [java] 1.0-rc3.1
     [java] default
     [java] ----------
     [java] ----------
     [java] Default locale: English (United States)
     [java] \* DEBUG: Locales are disabled or not found:
messages_en.properties
     [java] [DEBUG] Open context: C:\Users\brian.memoranda.context
     [java] [DEBUG] Open project manager:
C:\Users\brian.memoranda.projects
     [java] java.io.StreamCorruptedException: invalid stream header:
3C3F786D[DEBUG] Open task list:
C:\Users\brian.memoranda__default.tasklist
     [java] at
java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
     [java] at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
     [java] [DEBUG] Open note list:
C:\Users\brian.memoranda__default.notes
     [java] [DEBUG] Open resources list:
C:\Users\brian.memoranda__default.resources
     [java] at net.sf.memoranda.util.FileStorage.openTaskList(Unknown
Source)
     [java] at net.sf.memoranda.CurrentProject.<clinit>(Unknown Source)
     [java] at net.sf.memoranda.ui.ProjectsPanel.jbInit(Unknown Source)
     [java] at net.sf.memoranda.ui.ProjectsPanel.<init>(Unknown Source)
     [java] at net.sf.memoranda.ui.AppFrame.<init>(Unknown Source)
     [java] at net.sf.memoranda.ui.App.<init>(Unknown Source)
     [java] at net.sf.memoranda.Start.main(Unknown Source)
     [java] Exception in thread "main" java.lang.NullPointerException
     [java] at net.sf.memoranda.ui.TaskTableModel.getChildCount(Unknown
Source)
     [java] at
net.sf.memoranda.ui.treetable.AbstractTreeTableModel.isLeaf(Unknown Source)
     [java] at javax.swing.JTree.setModel(JTree.java:877)
     [java] at javax.swing.JTree.<init>(JTree.java:670)
     [java] at
net.sf.memoranda.ui.TaskTable$TreeTableCellRenderer.<init>(Unknown Source)
     [java] at net.sf.memoranda.ui.TaskTable.initTable(Unknown Source)
     [java] at net.sf.memoranda.ui.TaskTable.<init>(Unknown Source)
     [java] at net.sf.memoranda.ui.TaskPanel.<init>(Unknown Source)
     [java] at net.sf.memoranda.ui.DailyItemsPanel.<init>(Unknown Source)
     [java] at net.sf.memoranda.ui.WorkPanel.<init>(Unknown Source)
     [java] at net.sf.memoranda.ui.AppFrame.<init>(Unknown Source)
     [java] at net.sf.memoranda.ui.App.<init>(Unknown Source)
     [java] at net.sf.memoranda.Start.main(Unknown Source)
     [java] Java Result: 1
BUILD SUCCESSFUL
Total time: 51 seconds

It compiles but it doesn't run for me, because of a stream corruption error.

I think earlier you said I have to delete something... what was it again...
I'm trying to find the email

**Comment by tcatherm** [comment]
C:\Users\brian.memoranda
Delete that and the program will generate a new one. If you haven't deleted
it yet your task list stuff is probably still in XML which is causing the
problem.

**Comment by ghost** [comment]
Formal Code Review

[✓] Does the code completely and correctly implement the design?
[✓] Are there any redundancies in the code?
[✓] Is the code clearly and adequately documented?
[✓] Are all comments cohesive and easily understood for the code?
[✓] Are all variables properly defined with clear names?
[✓] Do all assigned variables have their appropriate types?
[✓] Correct return values where needed?
[✓] Are there any surplus or unused variables defined?
[✓] Proper use of arithmetic operations?
[✓] Proper use of loops and branches?
[✓] No unnecessary whitespace?
[✓] No syntax or compile errors?
[✓] Agreed Code Style followed?
    [✓] Static before non-static
    [✓] Public before package-private
    [✓] Package-private before protected
    [✓] Protected before private
    [✓] Members before methods
    [✓] Constructors before getters
    [✓] Getters before setters
    [✓] Setters before any non-constructor non-getter method
    [✗] Alphabetically
        Rule violated in createTask and duplicateTask in TaskListImpl because they are out of lexical order. Also, recursivelyModifyEffortFromSubTasks, recursivelyModifyStartDateFromSubTasks, and recursivelyModifyEndDateFromSubTasks are out of lexical order-- the same for their test cases in TaskImplTest.
    [✓] By parameter list size, from smallest to largest
    [✓] Curly bracket {} on their own line
    [✗] Accessor specifier with return values on one line, on their own
        TaskListImpl "public class" should occur on a line by itself. Ditto TaskImpl. The methods within TaskImpl also violate this rule.
    [✓] Throws keyword on own line
    [✗] Each element of a long ordered list of elements, such as a long parameter list or array   initialization on their own line
        A violation occurs in TaskListImpl as createTask has many parameters that should be put on different lines. Honestly, createTask is probably a code smell. A parameter object could be used here, or better yet just use the TaskImpl class itself as a parameter object and use duplicateTask instead of createTask-- it is effectively the same functionality if used that way.
    [✗] A space occurs before ( in a function invocation or definition
        Violations within duplicateTask andrecursivelyUpdateID in TaskListImpl, addSubTasksTest, recursivelyModifyXXX, removeXXX, getSubXXX, getRateTest in TaskImplTest, recursivelyModifyCompletionFromSubTasks and setProgress in TaskImpl. 
    [✓] Every method requires a javadoc block header with at least @param, and @return fields where appropriate

**Comment by ghost** [comment]
Alright I conducted a formal code review. There are some minor formatting
issues. The only non-trivial thing is whether we should even have a
createTask in TaskList

**Pull request closed without merging**
